### ISSUE TITLE
Add Updated Timestamp Column to Record Update Tables

### ISSUE THREAD

**Issue by koji-m** [route06inc/giselle#50]
## Overview
Add a column to specify the update timestamp for tables where record updates occur.

## Background
Currently, tables where record updates occur only have a column specifying the creation timestamp.
Tracking of changes is required.

## Tasks
- [x] List target tables
- [x] Execute migration in test environment and verify functionality
- [x] Update application code (if necessary)
- [x] Apply to production

## Considerations
Ensure that existing application logic is not affected.

**Comment by koji-m** [comment]
Currently, add a column that records record update timestamps only to tables that have record creation timestamps.

### tables to add `updated_at` column
- agents
- organizations
- teams
- ~requests~  --> Not used.
- ~files~  --> Not used.

**Comment by koji-m** [comment]
Close it as all tasks are completed.
